version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.0.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal:
      - run:
          command: az resource list
          name List resources of tenant stored as 'AZURE_SP_TENANT' env var
      - terraform/install:
          terraform_version: '1.2.3'
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      - terraform/destroy:
          path: .
workflows:
  example-workflow:
    jobs:
      - example-job
